import sys
from pathlib import Path

# Ensure project root is in path so imports work
ROOT = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT))

import streamlit as st
import pandas as pd
import time

from src.ids.config import alert_log


st.set_page_config(
    page_title="ML IDS Dashboard",
    layout="wide"
)

st.title("Machine Learning Intrusion Detection System")

st.markdown(
"""
SOC-style dashboard visualising alerts generated by the live IDS pipeline.
"""
)

# ===============================
# STATUS
# ===============================

st.subheader("System Status")

col1, col2, col3 = st.columns(3)

col1.success("IDS Pipeline Running")
col2.info("Model: Random Forest")
col3.info("Threshold: 0.20")

st.markdown("---")

flows = 0
alerts = 0
max_prob = 0

if alert_log.exists():

    df = pd.read_csv(alert_log)

    flows = df["flows"].sum()
    alerts = df["alerts"].sum()
    max_prob = df["max_prob"].max()

metric1, metric2, metric3 = st.columns(3)

metric1.metric("Flows Processed", flows)
metric2.metric("Alerts Detected", alerts)
metric3.metric("Highest Threat Probability", f"{max_prob:.3f}")

st.markdown("---")

# ===============================
# ALERT SEVERITY
# ===============================

st.subheader("Alert Severity Distribution")

if alert_log.exists():

    severity_counts = df["severity"].value_counts()

    st.bar_chart(severity_counts)

else:
    st.info("No alerts yet")

st.markdown("---")

# ===============================
# TOP ALERTS
# ===============================

st.subheader("Top Alerts")

if alert_log.exists():

    top_alerts = df.sort_values("max_prob", ascending=False)

    st.dataframe(top_alerts.head(10))

else:
    st.info("No alerts available")

st.markdown("---")

# ===============================
# FULL LOG
# ===============================

st.subheader("Alert Log")

if alert_log.exists():

    st.dataframe(df)

else:
    st.info("Alert log empty")

time.sleep(5)
st.rerun()