# Handles PCAP to CSV conversion, pcap file age checks and finding the correct
# Flow that has been created
import time
import subprocess
from pathlib import Path

#Return true if the file is old enough to assume it is ready to preprocess
def pcap_age_check(pcap_path: Path, age: float) -> bool:
    
    return (time.time() - pcap_path.stat().st_mtime) >= age

#Converts pcap into a CICFlowmeter CSV to allow model scoring
def pcap_csv_conversion(pcap_path: Path, flow_dir, cicflow_bat: Path) -> Path:
    output = flow_dir/(pcap_path.stem + ".csv")

    cmd = [
        "cmd", "/c",
        ".\\cfm.bat",
        str(pcap_path),
        str(output)
    ]

    completed = subprocess.run(
        cmd, cicflow_bat.parent, capture_output=True, text=True
    )

    if completed.returncode != 0:
        raise RuntimeError(
            f"CICFlowMeter failed for {pcap_path.name}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    
    return flow_dir


# Finds the CSV generated by CICFlowMeter for the pcap. Uses newest matching csv
# as a fallback
def find_csv(pcap_path: Path, flow_dir: Path) -> Path:
    matches = sorted(
        flow_dir.glob(f"{pcap_path.stem}*.csv"),
        key=lambda p: p.stat().st_mtime, reverse=True
    )
    
    if not matches:
        raise FileNotFoundError(f"No CSV found for {pcap_path.stem}")
    
    return matches[0]