# Handles PCAP to CSV conversion, pcap file age checks and finding the correct
# Flow that has been created

import time
import subprocess
from pathlib import Path


# Return true if the file is old enough to assume it is ready to preprocess
def pcap_age_check(pcap_path: Path, age: float) -> bool:
    return (time.time() - pcap_path.stat().st_mtime) >= age


# Converts pcap into a CICFlowmeter CSV to allow model scoring
def pcap_csv_conversion(pcap_path: Path, flow_dir: Path, cicflow_bat: Path) -> Path:

    flow_dir.mkdir(parents=True, exist_ok=True)  # Added safety

    cmd = [
        "cmd", "/c",
        str(cicflow_bat),  # FIX: previously hardcoded ".\\cfm.bat"
        str(pcap_path),
        str(flow_dir)
    ]

    completed = subprocess.run(
        cmd,
        cwd=cicflow_bat.parent,  # Ensures bat executes in correct directory
        capture_output=True,
        text=True
    )

    if completed.returncode != 0:
        raise RuntimeError(
            f"CICFlowMeter failed for {pcap_path.name}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )

    return flow_dir


# Finds the CSV generated by CICFlowMeter for the pcap
def find_csv(pcap_path: Path, flow_dir: Path) -> Path:

    preferred = sorted(
        flow_dir.glob(f"{pcap_path.stem}*.pcap_Flow.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )

    if preferred:
        return preferred[0]

    matches = sorted(
        [p for p in flow_dir.glob(f"{pcap_path.stem}*.csv") if p.is_file()],
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )

    if not matches:
        raise FileNotFoundError(f"No CSV found for {pcap_path.stem}")

    return matches[0]

# Checks that the CSV exists is old enough and can be opened
def csv_ready(csv_path: Path, min_age: float = 1.0) -> bool:

    if not csv_path.exists():
        return False

    if (time.time() - csv_path.stat().st_mtime) < min_age:
        return False

    try:
        with open(csv_path, "r", encoding="utf-8", errors="ignore"):
            return True
    except PermissionError:
        return False


def wait_for_real_csv(csv_path: Path, timeout: float = 10.0, check_interval: float = 0.5) -> bool:
    start = time.time()

    while time.time() - start < timeout:

        if csv_path.exists() and csv_path.is_file():

            try:
                with open(csv_path, "r", encoding="utf-8", errors="ignore"):
                    return True
            except PermissionError:
                pass

        time.sleep(check_interval)

    return False